// Login as a root user with password
POST http://localhost:3003/api/users/login
Content-Type: application/json

{
  "username": "root",
  "password": "erittainsalainen"
}

###
// root erittainsalainen
// muumipeikko muumimaailma
// akuankka  ankkalinna
// Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "muumipeikko",
  "name": "Muumi Peikko",
  "password": "muumimaailma"
}

###
// List all users
GET http://localhost:3003/api/users/getall

###
// List all blogs
GET http://localhost:3003/api/blogs

###
// Add a new blog entry with token and userID
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11dW1pcGVpa2tvIiwiaWQiOiI1ZWE1OGM4ZGIwMDQxNDQwNjA0MDE2NjgiLCJpYXQiOjE1ODc5MDc4NDh9.sg9Dvn3u0cc3N15KEKEZCltZxzHMKscFfTGyX2eWdiM

{
  "title": "Mennään Muumimaahan",
  "author": "Naantali",
  "url": "nadendahl.fi",
  "likes": 10,
  "userId": "5ea58c8db004144060401668"
}

###
// Delete a blog entry with token and userID
DELETE http://localhost:3003/api/blogs/5ea58d701b63244b88878572
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11dW1pcGVpa2tvIiwiaWQiOiI1ZWE1OGM4ZGIwMDQxNDQwNjA0MDE2NjgiLCJpYXQiOjE1ODc5MDc4NDh9.sg9Dvn3u0cc3N15KEKEZCltZxzHMKscFfTGyX2eWdiM

###
// Add a new comment
POST http://localhost:3003/api/blogs/5fac30b41c1deb18e4f11d49/comments
Content-Type: application/json

{
  "comment": "Ensimmäinen kommentti muumiblogiin Muumi Three"
}